---
title: config
description: Optimise software configurations.
privilege: TrustedInstaller
actions:
  - !task: { path: 'task\config\adobe-acrobat.yml' }
  - !task: { path: 'task\config\git.yml' }
  - !task: { path: 'task\config\ms-office.yml' }
