---
title: config-adobe-acrobat
description: Configure Adobe Acrobat to prevent malicious code execution.
privilege: TrustedInstaller
actions:
  - !writeStatus: { status: 'Configuring Adobe Acrobat' }

  - !registryKey:
    path: 'HKCU\SOFTWARE\Adobe'
    operation: add
    weight: 2
  - !registryKey:
    path: 'HKCU\SOFTWARE\Adobe\Acrobat Reader'
    operation: add
    weight: 2

  #=== Adobe Reader DC
  - !registryKey:
    path: 'HKCU\SOFTWARE\Adobe\Acrobat Reader\DC'
    operation: add
    weight: 2

  # Disable JavaScript.
  - !registryKey:
    path: 'HKCU\SOFTWARE\Adobe\Acrobat Reader\DC\JSPrefs'
    operation: add
    weight: 2
  - !registryValue:
    path: 'HKCU\SOFTWARE\Adobe\Acrobat Reader\DC\JSPrefs'
    value: 'bEnableJS'
    type: REG_DWORD
    data: '0'
    weight: 2

  # Secure file opening options.
  - !registryKey:
    path: 'HKCU\SOFTWARE\Adobe\Acrobat Reader\DC\Originals'
    operation: add
    weight: 2
  - !registryValue:
    path: 'HKCU\SOFTWARE\Adobe\Acrobat Reader\DC\Originals'
    value: 'bAllowOpenFile'
    type: REG_DWORD
    data: '0'
    weight: 2
  - !registryValue:
    path: 'HKCU\SOFTWARE\Adobe\Acrobat Reader\DC\Originals'
    value: 'bSecureOpenFile'
    type: REG_DWORD
    data: '1'
    weight: 2

  # Enable protected view and mode.
  - !registryKey:
    path: 'HKCU\SOFTWARE\Adobe\Acrobat Reader\DC\Privileged'
    operation: add
    weight: 2
  - !registryValue:
    path: 'HKCU\SOFTWARE\Adobe\Acrobat Reader\DC\Privileged'
    value: 'bProtectedMode'
    type: REG_DWORD
    data: '1'
    weight: 2
  - !registryKey:
    path: 'HKCU\SOFTWARE\Adobe\Acrobat Reader\DC\TrustManager'
    operation: add
    weight: 2
  - !registryValue:
    path: 'HKCU\SOFTWARE\Adobe\Acrobat Reader\DC\TrustManager'
    value: 'iProtectedView'
    type: REG_DWORD
    data: '1'
    weight: 2

  # Improve security for viewing PDFs in browsers and standalone.
  - !registryValue:
    path: 'HKCU\SOFTWARE\Adobe\Acrobat Reader\DC\TrustManager'
    value: 'bEnhancedSecurityInBrowser'
    type: REG_DWORD
    data: '1'
    weight: 2
  - !registryValue:
    path: 'HKCU\SOFTWARE\Adobe\Acrobat Reader\DC\TrustManager'
    value: 'bEnhancedSecurityStandalone'
    type: REG_DWORD
    data: '1'
    weight: 2

  #=== Adobe Reader XI
  - !registryKey:
    path: 'HKCU\SOFTWARE\Adobe\Acrobat Reader\XI'
    operation: add
    weight: 2

  # Disable JavaScript.
  - !registryKey:
    path: 'HKCU\SOFTWARE\Adobe\Acrobat Reader\XI\JSPrefs'
    operation: add
    weight: 2
  - !registryValue:
    path: 'HKCU\SOFTWARE\Adobe\Acrobat Reader\XI\JSPrefs'
    value: 'bEnableJS'
    type: REG_DWORD
    data: '0'
    weight: 2

  # Secure file opening options.
  - !registryKey:
    path: 'HKCU\SOFTWARE\Adobe\Acrobat Reader\XI\Originals'
    operation: add
    weight: 2
  - !registryValue:
    path: 'HKCU\SOFTWARE\Adobe\Acrobat Reader\XI\Originals'
    value: 'bAllowOpenFile'
    type: REG_DWORD
    data: '0'
    weight: 2
  - !registryValue:
    path: 'HKCU\SOFTWARE\Adobe\Acrobat Reader\XI\Originals'
    value: 'bSecureOpenFile'
    type: REG_DWORD
    data: '1'
    weight: 2
  - !registryKey:
    path: 'HKCU\SOFTWARE\Adobe\Acrobat Reader\XI\Privileged'
    operation: add
    weight: 2

  # Enable protected view and mode.
  - !registryValue:
    path: 'HKCU\SOFTWARE\Adobe\Acrobat Reader\XI\Privileged'
    value: 'bProtectedMode'
    type: REG_DWORD
    data: '1'
    weight: 2
  - !registryKey:
    path: 'HKCU\SOFTWARE\Adobe\Acrobat Reader\XI\TrustManager'
    operation: add
    weight: 2
  - !registryValue:
    path: 'HKCU\SOFTWARE\Adobe\Acrobat Reader\XI\TrustManager'
    value: 'iProtectedView'
    type: REG_DWORD
    data: '1'
    weight: 2

  # Improve security for viewing PDFs in browsers and standalone.
  - !registryValue:
    path: 'HKCU\SOFTWARE\Adobe\Acrobat Reader\XI\TrustManager'
    value: 'bEnhancedSecurityInBrowser'
    type: REG_DWORD
    data: '1'
    weight: 2
  - !registryValue:
    path: 'HKCU\SOFTWARE\Adobe\Acrobat Reader\XI\TrustManager'
    value: 'bEnhancedSecurityStandalone'
    type: REG_DWORD
    data: '1'
    weight: 2
