---
title: config
description: Configure Microsoft Office to prevent malicious code execution.
privilege: TrustedInstaller
actions:
  - !writeStatus: { status: 'Configuring Microsoft Office' }

  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office'
    operation: add
    weight: 2

  #=== Office 2007
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\12.0'
    operation: add
    weight: 2

  # Excel 2007
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\12.0\Excel'
    operation: add
    weight: 2

  # Prompt before opening files from an unknown publisher.
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\12.0\Excel\Security'
    operation: add
    weight: 2

  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\12.0\Excel\Security'
    value: 'PackagerPrompt'
    type: REG_DWORD
    data: '2'
    weight: 2

  # Disable macros and VBA code execution by default.
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\12.0\Excel\Security'
    value: 'VBAWarnings'
    type: REG_DWORD
    data: '4'
    weight: 2

  # Prompt for confirmation when opening workbooks with links.
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\12.0\Excel\Security'
    value: 'WorkbookLinkWarnings'
    type: REG_DWORD
    data: '2'
    weight: 2

  # PowerPoint 2007
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\12.0\PowerPoint'
    operation: add
    weight: 2

  # Prompt before opening files from an unknown publisher.
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\12.0\PowerPoint\Security'
    operation: add
    weight: 2

  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\12.0\PowerPoint\Security'
    value: 'PackagerPrompt'
    type: REG_DWORD
    data: '2'
    weight: 2

  # Disable macros and VBA code execution by default.
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\12.0\PowerPoint\Security'
    value: 'VBAWarnings'
    type: REG_DWORD
    data: '4'
    weight: 2

  # Word 2007
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\12.0\Word'
    operation: add
    weight: 2

  # Prompt before opening files from an unknown publisher.
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\12.0\Word\Options'
    operation: add
    weight: 2

  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\12.0\Word\Options\vpref'
    operation: add
    weight: 2

  # Disable automatic updating of links in Word documents.
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\12.0\Word\Options\vpref'
    value: 'fNoCalclinksOnopen_90_1'
    type: REG_DWORD
    data: '1'
    weight: 2

  # Prompt before opening files from an unknown publisher.
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\12.0\Word\Security'
    operation: add
    weight: 2

  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\12.0\Word\Security'
    value: 'PackagerPrompt'
    type: REG_DWORD
    data: '2'
    weight: 2

  # Disable macros and VBA code execution by default.
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\12.0\Word\Security'
    value: 'VBAWarnings'
    type: REG_DWORD
    data: '4'
    weight: 2

  #=== Office 2010
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\14.0'
    operation: add
    weight: 2

  # Excel 2010
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\14.0\Excel'
    operation: add
    weight: 2

  # Disable automatic updating of links in Excel workbooks.
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\14.0\Excel\Options'
    operation: add
    weight: 2

  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\14.0\Excel\Options'
    value: 'DontUpdateLinks'
    type: REG_DWORD
    data: '1'
    weight: 2

  # Prompt before opening files from an unknown publisher.
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\14.0\Excel\Security'
    operation: add
    weight: 2

  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\14.0\Excel\Security'
    value: 'PackagerPrompt'
    type: REG_DWORD
    data: '2'
    weight: 2

  # Disable macros and VBA code execution by default.
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\14.0\Excel\Security'
    value: 'VBAWarnings'
    type: REG_DWORD
    data: '4'
    weight: 2

  # Prompt for confirmation when opening workbooks with links.
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\14.0\Excel\Security'
    value: 'WorkbookLinkWarnings'
    type: REG_DWORD
    data: '2'
    weight: 2

  # PowerPoint 2010
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\14.0\PowerPoint'
    operation: add
    weight: 2

  # Prompt before opening files from an unknown publisher.
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\14.0\PowerPoint\Security'
    operation: add
    weight: 2

  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\14.0\PowerPoint\Security'
    value: 'PackagerPrompt'
    type: REG_DWORD
    data: '2'
    weight: 2

  # Disable macros and VBA code execution by default.
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\14.0\PowerPoint\Security'
    value: 'VBAWarnings'
    type: REG_DWORD
    data: '4'
    weight: 2

  #=== Word 2010
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\14.0\Word'
    operation: add
    weight: 2

  # Disable automatic updating of links in Word documents.
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\14.0\Word\Options'
    operation: add
    weight: 2

  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\14.0\Word\Options'
    value: 'DontUpdateLinks'
    type: REG_DWORD
    data: '1'
    weight: 2

  # Disable automatic updating of links in Word mail documents.
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\14.0\Word\Options\WordMail'
    operation: add
    weight: 2

  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\14.0\Word\Options\WordMail'
    value: 'DontUpdateLinks'
    type: REG_DWORD
    data: '1'
    weight: 2

  # Prompt before opening files from an unknown publisher.
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\14.0\Word\Security'
    operation: add
    weight: 2

  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\14.0\Word\Security'
    value: 'PackagerPrompt'
    type: REG_DWORD
    data: '2'
    weight: 2

  # Disable macros and VBA code execution by default.
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\14.0\Word\Security'
    value: 'VBAWarnings'
    type: REG_DWORD
    data: '4'
    weight: 2

  # Disable Dynamic Data Exchange (DDE) for added security.
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\14.0\Word\Security'
    value: 'AllowDDE'
    type: REG_DWORD
    data: '0'
    weight: 2

  #=== Office 2013
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\15.0'
    operation: add
    weight: 2

  # Excel 2013
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\15.0\Excel'
    operation: add
    weight: 2

  # Disable automatic updating of links in Excel workbooks.
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\15.0\Excel\Options'
    operation: add
    weight: 2

  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\15.0\Excel\Options'
    value: 'DontUpdateLinks'
    type: REG_DWORD
    data: '1'
    weight: 2

  # Prompt before opening files from an unknown publisher.
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\15.0\Excel\Security'
    operation: add
    weight: 2

  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\15.0\Excel\Security'
    value: 'PackagerPrompt'
    type: REG_DWORD
    data: '2'
    weight: 2

  # Disable macros and VBA code execution by default.
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\15.0\Excel\Security'
    value: 'VBAWarnings'
    type: REG_DWORD
    data: '4'
    weight: 2

  # Prompt for confirmation when opening workbooks with links.
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\15.0\Excel\Security'
    value: 'WorkbookLinkWarnings'
    type: REG_DWORD
    data: '2'
    weight: 2

  # PowerPoint 2013
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\15.0\PowerPoint'
    operation: add
    weight: 2

  # Prompt before opening files from an unknown publisher.
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\15.0\PowerPoint\Security'
    operation: add
    weight: 2

  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\15.0\PowerPoint\Security'
    value: 'PackagerPrompt'
    type: REG_DWORD
    data: '2'
    weight: 2

  # Disable macros and VBA code execution by default.
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\15.0\PowerPoint\Security'
    value: 'VBAWarnings'
    type: REG_DWORD
    data: '4'
    weight: 2

  # Word 2013
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\15.0\Word'
    operation: add
    weight: 2

  # Disable automatic updating of links in Word documents.
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\15.0\Word\Options'
    operation: add
    weight: 2

  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\15.0\Word\Options'
    value: 'DontUpdateLinks'
    type: REG_DWORD
    data: '1'
    weight: 2

  # Disable automatic updating of links in Word mail documents.
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\15.0\Word\Options\WordMail'
    operation: add
    weight: 2

  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\15.0\Word\Options\WordMail'
    value: 'DontUpdateLinks'
    type: REG_DWORD
    data: '1'
    weight: 2

  # Prompt before opening files from an unknown publisher.
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\15.0\Word\Security'
    operation: add
    weight: 2

  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\15.0\Word\Security'
    value: 'PackagerPrompt'
    type: REG_DWORD
    data: '2'
    weight: 2

  # Disable macros and VBA code execution by default.
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\15.0\Word\Security'
    value: 'VBAWarnings'
    type: REG_DWORD
    data: '4'
    weight: 2

  # Disable Dynamic Data Exchange (DDE) for added security.
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\15.0\Word\Security'
    value: 'AllowDDE'
    type: REG_DWORD
    data: '0'
    weight: 2

  #=== Office 2016
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\16.0'
    operation: add
    weight: 2

  # Excel 2016
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\16.0\Excel'
    operation: add
    weight: 2

  # Disable automatic updating of links in Excel workbooks.
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\16.0\Excel\Options'
    operation: add
    weight: 2

  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\16.0\Excel\Options'
    value: 'DontUpdateLinks'
    type: REG_DWORD
    data: '1'
    weight: 2

  # Prompt before opening files from an unknown publisher.
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\16.0\Excel\Security'
    operation: add
    weight: 2

  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\16.0\Excel\Security'
    value: 'PackagerPrompt'
    type: REG_DWORD
    data: '2'
    weight: 2

  # Disable macros and VBA code execution by default.
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\16.0\Excel\Security'
    value: 'VBAWarnings'
    type: REG_DWORD
    data: '4'
    weight: 2

  # Prompt for confirmation when opening workbooks with links.
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\16.0\Excel\Security'
    value: 'WorkbookLinkWarnings'
    type: REG_DWORD
    data: '2'
    weight: 2

  # PowerPoint 2016
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\16.0\PowerPoint'
    operation: add
    weight: 2

  # Prompt before opening files from an unknown publisher.
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\16.0\PowerPoint\Security'
    operation: add
    weight: 2

  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\16.0\PowerPoint\Security'
    value: 'PackagerPrompt'
    type: REG_DWORD
    data: '2'
    weight: 2

  # Disable macros and VBA code execution by default.
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\16.0\PowerPoint\Security'
    value: 'VBAWarnings'
    type: REG_DWORD
    data: '4'
    weight: 2

  # Word 2016
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\16.0\Word'
    operation: add
    weight: 2

  # Disable automatic updating of links in Word documents.
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\16.0\Word\Options'
    operation: add
    weight: 2

  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\16.0\Word\Options'
    value: 'DontUpdateLinks'
    type: REG_DWORD
    data: '1'
    weight: 2

  # Disable automatic updating of links in Word mail documents.
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\16.0\Word\Options\WordMail'
    operation: add
    weight: 2

  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\16.0\Word\Options\WordMail'
    value: 'DontUpdateLinks'
    type: REG_DWORD
    data: '1'
    weight: 2

  # Prompt before opening files from an unknown publisher.
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\16.0\Word\Security'
    operation: add
    weight: 2

  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\16.0\Word\Security'
    value: 'PackagerPrompt'
    type: REG_DWORD
    data: '2'
    weight: 2

  # Disable macros and VBA code execution by default.
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\16.0\Word\Security'
    value: 'VBAWarnings'
    type: REG_DWORD
    data: '4'
    weight: 2

  # Disable Dynamic Data Exchange (DDE) for added security.
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\16.0\Word\Security'
    value: 'AllowDDE'
    type: REG_DWORD
    data: '0'
    weight: 2

  #=== Commons
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\Common'
    operation: add
    weight: 2

  # Disable all ActiveX controls.
  - !registryKey:
    path: 'HKCU\SOFTWARE\Microsoft\Office\Common\Security'
    operation: add
    weight: 2

  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Office\Common\Security'
    value: 'DisableAllActiveX'
    type: REG_DWORD
    data: '1'
    weight: 2
