---
title: tweak-security
description: Tweaks system security settings.
privilege: TrustedInstaller
actions:
  - !writeStatus: { status: 'Tweaking security settings.' }

  # Block known vulnerable drivers.
  - !registryValue:
    path: 'HKLM\SYSTEM\CurrentControlSet\Control\CI\Config'
    value: 'VulnerableDriverBlocklistEnable'
    type: REG_DWORD
    data: '1'
    weight: 2

  # Enable TCG security for storage data protection.
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\EnhancedStorageDevices'
    value: 'TCGSecurityActivationDisabled'
    type: REG_DWORD
    data: '0'
    weight: 2

  # Disable automatic Wi-Fi Sense connections to avoid harmful networks.
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\PolicyManager\default\WiFi\AllowAutoConnectToWiFiSenseHotspots'
    value: 'value'
    type: REG_DWORD
    data: '0'
    weight: 2

  # Disable delivery optimisation to prevent malicious injections.
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\DeliveryOptimization\Config'
    value: 'DownloadMode'
    type: REG_DWORD
    data: '0'
    weight: 2

  # Disable SMB to protect against crypt-worms.
  - !cmd:
    command: 'sc config lanmanworkstation depend= bowser/mrxsmb20/nsi'
    wait: true
    weight: 8

  - !cmd:
    command: 'sc config mrxsmb10 start= disabled'
    wait: true
    weight: 8

  - !registryValue:
    path: 'HKLM\SYSTEM\CurrentControlSet\services\LanmanServer\Parameters'
    value: 'SMB1'
    type: REG_DWORD
    data: '0'
    weight: 2

  - !registryValue:
    path: 'HKLM\SYSTEM\CurrentControlSet\services\mrxsmb10'
    value: 'Start'
    type: REG_DWORD
    data: '4'
    weight: 2

  - !registryValue:
    path: 'HKLM\SYSTEM\CurrentControlSet\Services\LanmanWorkstation'
    value: 'DependOnService'
    type: REG_MULTI_SZ
    data: 'Bowser\0MRxSmb20\0NSI'
    weight: 2

  # Disable AutoRun to prevent malicious code execution.
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer'
    value: 'NoDriveTypeAutoRun'
    type: REG_DWORD
    data: '181'
    weight: 2

  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\AutoplayHandlers'
    value: 'DisableAutoplay'
    type: REG_DWORD
    data: '1'
    weight: 2

  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer'
    value: 'NoAutorun'
    type: REG_DWORD
    data: '1'
    weight: 2

  # Install apps from any downloads directory.
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Attachments'
    value: 'SaveZoneInformation'
    type: REG_DWORD
    data: '1'
    weight: 2

  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Attachments'
    value: 'SaveZoneInformation'
    type: REG_DWORD
    data: '1'
    weight: 2

  # Install apps with unsigned certificates.
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\safer\codeidentifiers'
    value: 'authenticodeenabled'
    type: REG_DWORD
    data: '0'
    weight: 2

  # Disable SmartScreen.
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\AppHost'
    value: 'ContentEvaluation'
    type: REG_DWORD
    data: '0'
    weight: 2

  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer'
    value: 'SmartScreenEnabled'
    type: REG_SZ
    data: 'Off'

  # Hiding last logged-in username on lock screen.
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System'
    value: 'dontdisplaylastusername'
    type: REG_DWORD
    data: '1'
    weight: 2

  # Hiding tips on lock screen.
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Search'
    value: 'HasAboveLockTips'
    type: REG_DWORD
    data: '0'
    weight: 2
